### ISSUE TITLE
How to use antiforgery in SLB without session keeping?

### ISSUE THREAD

**Issue by Kagamine** [aspnet/Antiforgery#100]
It seems that the tokens are stored in local machine, how to make it store in Redis or a distributed environment?

**Comment by rynowak** [comment]
Antiforgery or CSRF protection is a mitigation for attacks where a user's credentials are persistent on the local machine, such as in a cookie. Nothing on the server side today *stores* the antiforgery tokens, they are encrypted data that can be read later by the server.

What is it that you're really trying to do?

**Comment by Eilon** [comment]
@alexsandro-xpt the tokens will definitely work across machines in a cluster if the machines are configured correctly for a web farm. Here's a doc on this topic: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/web-farm?view=aspnetcore-2.1

In particular, the "Data Protection" section is what is relevant to anti forgery tokens.
