### ISSUE TITLE
Cookie path is always / in IIS

### ISSUE THREAD

**Issue by wanton7** [aspnet/Antiforgery#101]
When you put your application to virtual directory named myvirtualpath in IIS, antiforgery cookie is still using / as path and not /myvirtualpath.

**Comment by blowdart** [comment]
Yup, that's wrong :)

**Comment by rynowak** [comment]
This is definitely a bug.

Have you hit an issue that you need help working around?

**Comment by wanton7** [comment]
If that comment was meant for me. I made couple of Asp.Net Core for company only for our own use currently, so this is not a big problem for me.

After this is fixed those people who have used these applications made with version that used / as path might have problem. Because you can have cookies with a same name at / and at /myvirtualpath. After you remove one from /myvirtualpath application will see one from /.

So you should probably include this info somewhere for people to see as breaking change :)
