### ISSUE TITLE
Handling a failed validation

### ISSUE THREAD

**Issue by strohhut** [aspnet/Antiforgery#112]
When I use `UseStatusCodePagesWithReExecute` and get a 404 is there any way I can know that the cause is that the validation of the antiforgery token failed?

I tried getting this information via `Features` but it was no success:

```CSharp
[Route("~/Error/{code}")]
public IActionResult Error(string code /*400 when validation failed*/)
{
    var itsNull1 = HttpContext.Features.Get<IAntiforgery>();
    var itsNull2 = HttpContext.Features.Get<IAntiforgeryAdditionalDataProvider>();
    var itsNull3 = HttpContext.Features.Get<IAntiforgeryFeature>();
    var itsNull4 = HttpContext.Features.Get<AntiforgeryFeature>();
    var itsNull5 = HttpContext.Features.Get<AntiforgeryValidationException>();

    var status = Response.StatusCode; // 200 when validation failed
    ...
```

One thing I found is that normally the following is true inside the `Error` action: `code = Response.StatusCode.ToString()`. It's true for instance when I return a 400 StatusCodeResult myself from an action. Now when the `Error` action is executed because the token validation failed then `code` is `"400"` and `Response.StatusCode` is `200` for some reason.

Is it safe to assume that when `code == "400" && Response.StatusCode == 200` Antiforgery is responsible?

**Comment by strohhut** [comment]
I found that my `ErrorController` isn't called at all after a failed validation if I have `services.AddAntiforgery` before `services.AddAuthentication(); services.AddAuthorization();` inside `ConfigureServices`.

**Comment by Eilon** [comment]
Can you provide more info on what you are trying to achieve? Is it to produce a custom error page specifically for antiforgery failures? Or some other scenario?

**Comment by strohhut** [comment]
Currently I require it for logging because I want to know when post requests fail due to Antiforgery. A custom error page would make sense too because on my page post requests fail after a server restart if the page was loaded before the server restart due to Antiforgery. 

If there was a server restart recently It would be nice to include something in the error page like "Oops we just made an update. Please try again" so it doesn't look like a random error.

Other components provide features like `IStatusCodeReExecuteFeature` or `IExceptionHandlerFeature` in order to tell me why my error action is executing. It would be nice if Antiforgery would do this too.

**Comment by Eilon** [comment]
@rynowak @Tratcher thoughts on how to handle this cleanly?

**Comment by Tratcher** [comment]
If your antiforgery is failing due to server restarts then your DataProtection is not setup correctly. Let's address that issue first.

This is the most common cause:
https://docs.microsoft.com/en-us/aspnet/core/publishing/iis#create-a-data-protection-registry-hive

**Comment by rynowak** [comment]
If this is just about logging we already log this information https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/Internal/ValidateAntiforgeryTokenAuthorizationFilter.cs#L45

However it does seem useful to be able to handle antiforgery errors in a special way

**Comment by strohhut** [comment]
@Tratcher 
I didn't know that it's supposed to work after restarts. I have `services.AddDataProtection` at the beginning of `ConfigureServices`. I don't know if the problim exists on my prod system (where keys are under HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ASP.NET\4.0.30319.0\AutoGenKeys\...\DataProtection). I'll test this when I have to make a restart next time. 
I'm seing the problem on my dev system (keys are under %LOCALAPPDATA%\ASP.NET\DataProtection-Keys). Decrypting cookies after a restart works on both systems. Maybe Antiforgery isn't picking up the key?

@rynowak 
Yeah, but custom logging might be desired for things like adjusting the log level of Antiforgery messages based on some context info.

**Comment by rynowak** [comment]
@strohhut - agreed, we need to provide some way to know about a failed antiforgery. I was mentioning the logging in case you weren't aware of it.

**Comment by Tratcher** [comment]
If cookies are working then anti-forgery should be working. It would help if you could capture the error.

The best point of control for this is probably the MVC filter that invokes the service, handles the exception, and generates the response.

**Comment by Eilon** [comment]
We're looking to improve this experience for MVC in https://github.com/aspnet/Mvc/issues/6678. For antiforgery cases outside of MVC, it's up to whoever calls antiforgery to flow errors however they want.
