### ISSUE TITLE
Skip anti forgery validation for non-browser clients

### ISSUE THREAD

**Issue by hikalkan** [aspnet/Antiforgery#115]
As I know, CSRF is only problem for browsers with cookie based authentication (since cookies are sent in a cross site request).

Think that we added global ``AutoValidateAntiforgeryTokenAttribute`` to protect out application. What if we want to use same controllers (API controllers) from a mobile application (or from postman for tests). In that case, we don't want to send antiforgery token in the cookie, because it's not a security problem for these clients, and it's hard to do it.

The problem is this code: https://github.com/aspnet/Antiforgery/blob/dev/src/Microsoft.AspNetCore.Antiforgery/Internal/DefaultAntiforgery.cs#L160

It throws exception if antiforgery cookie is not sent. My suggestion is to assume the request valid if this cookie is not present. Because, a cross-site request can not prevent to send this cookie (and just send the auth cookie).

What do you think?

**Comment by brockallen** [comment]
Use tokens instead to protect your endpoints. That's what you have to do if you want to support both browser and non-browser clients.

**Comment by hikalkan** [comment]
But we may have an MVC project which both provides UI and API in single endpoint. In that case, we would want to apply anti forgery for browsers but not for other clients. I believe many developers in this case.
Also it's native to use token auth for a SPAs, but not always possible for multi-page applications.

**Comment by brockallen** [comment]
> In that case, we would want to apply anti forgery for browsers but not for other clients.

So how do you verify that?

**Comment by hikalkan** [comment]
I explained it in my first post:

> assume the request valid if this cookie is not present. Because, a cross-site request can not prevent to send this cookie.

So, if a cross site will make a hack request, then it will automatically send the antiforgery cookie too.

**Comment by brockallen** [comment]
So then the antiforgery has to know what other cookie to look for to know if should run? G'd luck getting them to agree to this :)

**Comment by hikalkan** [comment]
My recommendation is so simple: Just return without exception if Cookie is null: https://github.com/aspnet/Antiforgery/blob/dev/src/Microsoft.AspNetCore.Antiforgery/Internal/DefaultAntiforgery.cs#L160
No need to know another cookie. It's already knowing the Cookie which should carry the token.

**Comment by Eilon** [comment]
There are no plans to make product changes to enable this. You could choose not to use `AutoValidateAntiforgeryTokenAttribute`, and then selectively enable antiforgery via your own application logic.

**Comment by biggyspender** [comment]
This strategy is a failure because while the antiforgery token is delivered as a session cookie, the authentication cookie might have a considerably longer lifespan.

        protected override bool ShouldValidate(AuthorizationFilterContext context)
        {
            if (!base.ShouldValidate(context))
            {
                return false;
            }

            //No need to validate if antiforgery cookie is not sent.
            //That means the request is sent from a non-browser client.
            //See https://github.com/aspnet/Antiforgery/issues/115
            if (!context.HttpContext.Request.Cookies.ContainsKey(_options.CookieName))
            {
                return false;
            }

            // Anything else requires a token.
            return true;
        }
    }

The premise made above : "No need to validate if antiforgery cookie is not sent" is a broken vulnerability.

After restarting the browser, it will be possible to forge a post with a long-lived auth cookie ("remember me?") and no anti-forgery token (it was deleted when the browser closed). Perfect for at least one post (until the new antiforgery cookie is sent in the response).

**Comment by schmitch** [comment]
@biggyspender however that case could be prevented, if ShouldValidate would actually check the Auth Cookie **and** the CSRF Token.
