### ISSUE TITLE
Question: `no-store` versus `no-cache` for Antiforgery

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Antiforgery#116]
This question is related to how caching and Antiforgery was handled for https://github.com/aspnet/Antiforgery/issues/105.

Looking at https://github.com/aspnet/Antiforgery/blob/3fc090e2fee47884af7968031e40876fcb6549ae/src/Microsoft.AspNetCore.Antiforgery/Internal/DefaultAntiforgery.cs#L70-L72 ...

> Explicitly set the cache headers to 'no-cache'. This could override any user set value but this is fine as a response with antiforgery token must never be cached.

and thus `SetDoNotCacheHeaders()` ...
https://github.com/aspnet/Antiforgery/blob/3fc090e2fee47884af7968031e40876fcb6549ae/src/Microsoft.AspNetCore.Antiforgery/Internal/DefaultAntiforgery.cs#L370-L379

@JunTaoLuo said [ref](https://github.com/aspnet/Antiforgery/issues/105#issuecomment-252769270) ...
> The proposal is to disable caching when antiforgery is used regardless of whether cookies are being set. 

[RFC 7234](https://tools.ietf.org/html/rfc7234) doesn't guarantee that storage will not occur tho ...

> 5.2.1.4.  no-cache
> The "no-cache" request directive indicates that a cache MUST NOT use a stored response to satisfy the request without successful validation on the origin server.

Wondering: Why doesn't Antiforgery set `no-store` rather than `no-cache`?

**Comment by shaunluttin** [comment]
Setting `no-store` would help in cases when the user clicks the browser's back button.

**Comment by JunTaoLuo** [comment]
I suppose the language in the in-line comment isn't completely clear but we wanted to prevent serving cached content when antiforgery is being used. `no-cache` would have been sufficient for this since the response cannot be served unless validated with the origin which should generate a new response. However, as a precaution, we might want to consider also sending `no-store` to prevent any storage of the response in the first place.

> Setting no-store would help in cases when the user clicks the browser's back button.

The language in https://tools.ietf.org/html/rfc7234#section-6 is still a little ambiguous (but much better than rfc 2616). "This does not prohibit the history mechanism from telling the user that a view might be stale or from honoring cache directives (e.g., Cache-Control: no-store)." This suggests that cache directives should be honored but the older versions of some browsers did not since they treated history lists and caches differently (e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=441751). 

cc @muratg 

Also consider referring to http://stackoverflow.com/questions/49547/how-to-control-web-page-caching-across-all-browsers for other headers we might want to send for compatibility with more/older browsers.

**Comment by shaunluttin** [comment]
> we wanted to prevent serving cached content when antiforgery is being used.

Does that intent include preventing serving cached content when the user clicks the back button?

**Comment by muratg** [comment]
I think we should do this one as well.  @Eilon @rynowak thoughts?

**Comment by snluu** [comment]
@kichalla When will the fix for this be released?

**Comment by Eilon** [comment]
@snluu it will be in the 2.0 release of ASP.NET Core, which will be out later this year. We'll have previews before then, though.

**Comment by snluu** [comment]
@Eilion :( that's unfortunate. Can we ship this out as a bug fix (1.1.2), or can you suggest a workaround? The page I'm working on requires "no-store", but unfortunately is always overwritten by Antiforgery with "no-cache".

**Comment by Eilon** [comment]
@snluu I think you should be able to just set that header as well wherever you use anti-forgery, right? You could perhaps encapsulate this in your own filter attribute / HTML helper or wherever it is that you need this.

**Comment by snluu** [comment]
Antiforgery is able to override that, unfortunately. I have have this class below, and confirmed that the code was executed and set the header, and then the header got overwritten by Antiforgery:
```
    internal sealed class NoCacheAttribute : ActionFilterAttribute
    {
        public bool NoStore { get; set; }

        public override void OnResultExecuting(ResultExecutingContext context)
        {
            if (NoStore)
            {
                context.HttpContext.Response.Headers["Cache-Control"] = "no-cache, no-store, max-age=0";
            }
            else
            {
                context.HttpContext.Response.Headers["Cache-Control"] = "no-cache, max-age=0";
            }

            context.HttpContext.Response.Headers["Pragma"] = "no-cache";
            context.HttpContext.Response.Headers["Expires"] = "-1";

            base.OnResultExecuting(context);
        }

    }
```

**Comment by snluu** [comment]
@Eilon Antiforgery is able to override that, unfortunately. I have have this class below, and confirmed that the code was executed and set the header, and then the header got overwritten by Antiforgery:
```
    internal sealed class NoCacheAttribute : ActionFilterAttribute
    {
        public bool NoStore { get; set; }

        public override void OnResultExecuting(ResultExecutingContext context)
        {
            if (NoStore)
            {
                context.HttpContext.Response.Headers["Cache-Control"] = "no-cache, no-store, max-age=0";
            }
            else
            {
                context.HttpContext.Response.Headers["Cache-Control"] = "no-cache, max-age=0";
            }

            context.HttpContext.Response.Headers["Pragma"] = "no-cache";
            context.HttpContext.Response.Headers["Expires"] = "-1";

            base.OnResultExecuting(context);
        }

    }
```

**Comment by shaunluttin** [comment]
@snluu We have had some success using the following code: 

```

**Comment by snluu** [comment]
@shaunluttin, fantastic! Thanks for the workaround. 

@Eilon I'm sure a lot of folks will be grateful to have this (and maybe other items with the bug tag) rolled out to an update before 2.0 :)

**Comment by Jak893** [comment]
I came across the same issue today and couldn't seem to get the workaround proposed by @shaunluttin to work. In the end I ended up implementing the `IAntiforgery` service and then internally constructing the `DefaultAntiforgery` class, this allowed me to change what I needed in the headers, a little overkill but seems to be working fine for me now.

```C#
namespace CPC.Mx.Common
{
    public class MXAntiforgery : IAntiforgery
    {
        private readonly DefaultAntiforgery _default;

        public MXAntiforgery(IOptions<AntiforgeryOptions> antiforgeryOptionsAccessor,
            IAntiforgeryTokenGenerator tokenGenerator,
            IAntiforgeryTokenSerializer tokenSerializer,
            IAntiforgeryTokenStore tokenStore,
            ILoggerFactory loggerFactory)
        {
            _default = new DefaultAntiforgery(antiforgeryOptionsAccessor,
                tokenGenerator,
                tokenSerializer,
                tokenStore,
                loggerFactory);
        }

        public AntiforgeryTokenSet GetAndStoreTokens(HttpContext httpContext)
        {
            var result = _default.GetAndStoreTokens(httpContext);
            httpContext.Response.Headers[HeaderNames.CacheControl] = new StringValues(new[] { "no-cache", "max-age=0", "must-revalidate", "no-store" });
            httpContext.Response.Headers[HeaderNames.Pragma] = "no-cache";

            return result;
        }

        public AntiforgeryTokenSet GetTokens(HttpContext httpContext)
        {
            return _default.GetTokens(httpContext);
        }

        public Task<bool> IsRequestValidAsync(HttpContext httpContext)
        {
            return _default.IsRequestValidAsync(httpContext);
        }

        public Task ValidateRequestAsync(HttpContext httpContext)
        {
            return _default.ValidateRequestAsync(httpContext);
        }

        public void SetCookieTokenAndHeader(HttpContext httpContext)
        {
            _default.SetCookieTokenAndHeader(httpContext);
        }
    }
}
```
Lastly I just registered this in Startup using `services.AddSingleton<IAntiforgery, MXAntiforgery>();`
