### ISSUE TITLE
Invalidate Tokens

### ISSUE THREAD

**Issue by renevangeffen** [aspnet/Antiforgery#123]
I'm using Antiforgery for a site we're building for a large insurer, I just received the results of a security audit, the auditor insists the request token should be invalidated on each request. I cannot find a way to enforce new tokens for every request. Can someone tell me if this is possible and how? If its not possible would you consider adding it?

**Comment by blowdart** [comment]
It's not possible, and it's a little weird to be honest. You'd break tabbed browsing.

I'm somewhat confused about what the auditor thinks this will protect against. The only time I'd invalidate tokens is when authentication happens, at login or at logout and we do that already.

Some reading that supports our approach - https://security.stackexchange.com/questions/22903/why-refresh-csrf-token-per-form-request https://stackoverflow.com/questions/10466241/new-csrf-token-per-request-or-not https://stackoverflow.com/questions/8655817/csrf-protection-do-we-have-to-generate-a-token-for-every-form

**Comment by blowdart** [comment]
Thinking a little more, it would be possible, maybe, by writing a one use data protector (in much the same way we have a time limited data protector), but it'd also take some work inside the anti forgery also. Given the security advantages of this are unclear, I don't think it's something we'd take on, unless we had a clear explanation of what benefits it would give.

**Comment by renevangeffen** [comment]
Thanks for your reply. Unfortunately the auditor didn't give me an explanation as to why he thinks there should be per-request tokens. I'll forward the information you provided to the auditor.
I'll close the issue because it isn't really an issue. Thanks again.
