### ISSUE TITLE
RequireSsl not setting cookie to secure

### ISSUE THREAD

**Issue by thecarlo** [aspnet/Antiforgery#134]
I'm having great difficulty setting the anti forgery cookie to secure on .NET Core using Microsoft.AspNetCore.Antiforgery 1.1.1. 

Setting RequireSsl = true does not set the cookie to secure.

Steps taken to reproduce :
1) Set up Kestrel to use SSL
![kestrel-ssl](https://cloud.githubusercontent.com/assets/5310264/24699843/a4ae041a-19f5-11e7-88d4-ff4fae9d7e67.png)

2) Add AntiForgery middleware
`services.AddAntiforgery(
                opts =>
                {
                    opts.CookieName = "_af";
                    opts.RequireSsl = true;
                }
            );`

3) Use chrome to check if cookie set to secure
![af-secure](https://cloud.githubusercontent.com/assets/5310264/24699763/5ecb8454-19f5-11e7-9f38-fb687bcc3ce7.png)

Having browsed through the source code, it's my understanding that the main purpose of the RequireSsl = true option is to ensure an error is thrown / anti-forgery request will fail if the request is not served over SSL/TLS.

However, the code at https://github.com/aspnet/Antiforgery/blob/2fcb187d7d34e9a0b046c2502c3a8b9b0155db91/src/Microsoft.AspNetCore.Antiforgery/Internal/DefaultAntiforgeryTokenStore.cs clearly makes an attempt to set the cookie to secure if RequireSsl = true.

![antiforgery-secure-true](https://cloud.githubusercontent.com/assets/5310264/24699977/1aca85d8-19f6-11e7-8af3-e8785f5d21de.png)

**Comment by thecarlo** [comment]
Closing this issue - it seems to have been resolved in the latest release

**Comment by BharatRajMeriyala** [comment]
When you say latest release, can you tell me which version? is that 1.1.2? Since 2.0.0 is compatible with Dotnet Core 1.1. Please guide me.
