### ISSUE TITLE
Load balancing - reducing the Data Protection API configuration overhead

### ISSUE THREAD

**Issue by a-h** [aspnet/Antiforgery#143]
I've been setting up a .NET Core MVC 6 application to run behind a load balancer. The platform is Docker containers on Linux.

Reading through the configuration for CSRF, it looks like I'd have to setup a Redis cluster, a UNC share or some other service because the CSRF relies on the Data Protection API. (https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview).

This was a bit of surprise given that the previous .Net experience was to just synchronise the machine keys across a cluster. Other platform implementations I've seen (e.g. https://github.com/gorilla/csrf) are based on symmetric encryption keys passed in as configuration, which is pretty straightforward to setup.

So I created a custom implementation of the `IAntiforgery` interface which:
 * Creates a 'token' consisting of a guid concatenated with an expiry date (in ticks), e.g.:
   * e2d41ea8-d429-4a97-9c0c-ff3bdac0f18d_21367216378267
   * (The guid makes it so that each request is unique, the expiry makes it so it's not possible to get a single CSRF token and use it forever across multiple requests.)
 * Sets the form value to the cleartext.
 * Encrypts the 'token' using AES with symmetric keys (iv and key) provided as parameters and sets it as the cookie (base64 encoded).
 * On form post etc., decodes and decrypts the cookie then compares the plaintext to the form post submitted in the plain.
  * If one of the values is missing, the decryption fails, or if the decrypted values don't match, then throw an `AntiforgeryValidationException`.
  * If the expiry date has passed, then throw an `AntiforgeryValidationException`.

This means there's no effort in setting up extra infrastructure, and the configuration is pretty easy. My implementation can just be slotted into the existing system:

```c#
services.AddScoped<IAntiforgery, AesAntiforgery>(p => new AesAntiforgery(p.GetService<ILogger<AesAntiforgery>>(), config.Key, config.IV, TimeSpan.FromHours(12)));
```

I'm happy to open source as-is, or I'd be happy to put an extra day or so's work in to make it fit into the existing code base if there's interest in a pull request?

Thoughts?

**Comment by a-h** [comment]
I've posted the code here: https://github.com/a-h/AspNetCore.Antiforgery.Aes

**Comment by a-h** [comment]
Made a package here: https://www.nuget.org/packages/AspNetCore.Antiforgery.Aes

**Comment by blowdart** [comment]
So we specifically moved away from a fixed key as a design decision. this would be a step back to the mess that was machine key. Whilst I appreciate the thought and the effort this has the same rotation problem that machine key has. Given DataProtection is used for a bunch of stuff other than CSRF, having CSRF become  config based may end up introducing even more confusion when it works and, for example, authentication doesn't.

**Comment by a-h** [comment]
Sure, I get the benefit of the key rotation but just so you know why I care about this, this is the thought process:

* Noticed that the new HTML tag helpers render the CSRF validation token by default and assumed that this meant that they also get validated
  - (From my later testing I found that they don't unless you add a global filter or attribute to an individual controller method, which was a bit surprising)
* Discussed with a coworker how this could work across a load balanced set of machines
   * Does it use a hash of the assembly to drive the token?
   * It can't use the machine key, so what does it do?
* Found #19 relating to CSRF validation across load balanced sets which pointed to the documentation at https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview
   * UNC shares sounds a bit Windows only
   * Redis sounds like something that could work

Starting thinking it through...

- Disable CSRF protection
   - Easy, but reduces security
- Implement an alternative
   - Probably 10 hours effort
   - It would be a bit unusual
   - It's not feature delivery for my client, so I'd rather not if I don't need to
- Configure Data Protection API:
   - Find answers to:
      - What would happen when keys rotate? 
         - Would the apps stop being able to validate CSRF?
      - When do keys rotate? Who chooses? Can any of the Web applications do it? Which would decide? Is there a consensus algorithm like Paxos at play, or a locking process? Can multiple keys be valid at once, e.g. what if server A rotates keys, how long will it take for server B to notice that key rotation has occurred?
   - Configure Data Protection API to use Redis?
      - Set up a Redis cluster in Dev, UAT and Live environments
      - Reconfigure Firewall rules to allow the Web applications to connect to the new Redis cluster
      - Configure monitoring and alerting on the Redis infrastructure
      - Document the new Redis system and provide DR instructions
      - Test the new failure modes (e.g. what happens when Redis fails, how does Redis failover), Redis isn't consensus protocol driven, so it's potentially a human step to resolve issues
      - Consider setting up a Redis proxy to authenticate Redis
   - Configure Data Protection API to use a UNC share?
      - Sounds like something that would only work on Windows?
      - Sounds like I'd have to maybe open some firewall ports.
      - Setup some sort of SMB share, not sure how this would work, how this would scale
      - Would it need to use file locking mechanisms? Would these work on Linux filesystems which don't lock files.
      - Mount a readonly directory containing static keys and get the apps to load Data Protection API state from that?

So at this point, it looked like to use the built-in CSRF protection my stateless Web tier would need to become a distributed system and have some shared state across it. I'd also have to do a lot of research (the documentation isn't very detailed) and take on a bunch of known and unknown failure modes.

This isn't very attractive to me - I'd rather have reduced infrastructure configuration (which also reduces possible failure modes) and have to handle key rotation myself. My Web containers are generally running for a couple of weeks at most without a release, and I can automate creation of new keys at release time easily, so it's much simpler than having to understand how the Data Protection API works across multiple machines. I thought it would be faster and simpler for me to write an alternative implementation.

I didn't think that my implementation would replace the default, but I think it's worth considering how taking a dependency on the Data Protection API for CSRF protection results in a larger operational overhead (e.g. setting up a redis cluster, configuring network and storage (if you use UNC), setting up monitoring and deployment) and cognitive overhead (working out how it all works) and whether most users are willing / able to accept that.

Just some thoughts from a user. Happy to close!

**Comment by Eilon** [comment]
@blowdart - would we make any changes in this space? If not, we should close.

**Comment by blowdart** [comment]
I'm learning towards no, unless we get a much greater volume of people saying this sucks right now.

**Comment by shairozan** [comment]
I'm going to be clear that this sucks. I haven't worked with a modern framework in any language that forces this issue back into infrastructure when it could be handled via configuration. I get your point that systems other than CSRF use the data protection API, but I second the notion that I would rather manage key rotation myself than add an entire subsystem in infrastructure to manage this.
