### ISSUE TITLE
GetAndStoreTokens(...).CookieToken seems to always be null

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Antiforgery#152]
Take the following example:

```C#
app.Run(async (context) =>
{
    var antiforgery = context.RequestServices.GetRequiredService<IAntiforgery>();

    // The token.CookieToken is always null
    await context.Response.WriteAsync("<p>Cookie Token: " + token.CookieToken + "</p><br />");
});
```

I'm not confident as to how many valid scenarios utilize the `token.CookieToken` but it's a blatant issue nevertheless.

**Comment by NTaylorMullen** [comment]
Did a deep investigation of this and the root cause of the issue Is that we always utilize newly created cookie tokens when creating our AntiforgeryTokenSet… This means that after the first request there’s no “new” cookie token and it therefore returns null.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2417
