### ISSUE TITLE
AntiforgeryTokenSet should have a CookieName property

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Antiforgery#153]
It has `HeaderName` which is retrievable; it should also have `CookieName`.

**Comment by Eilon** [comment]
@NTaylorMullen - any idea of a scenario where this might matter a lot? Or is it more about consistency and/or theoretical case?

**Comment by NTaylorMullen** [comment]
In scenarios where cookies may have been reconstructed prior to sending a request you have to rely on convention (setting a magic string on both the client and server) to get Antiforgery to work. It's uncommon but occurs in JavaScript/custom http clients/other API services that don't maintain cookies across requests.

**Comment by Eilon** [comment]
> reconstructed prior to sending a request

What exactly does that mean? Wouldn't the client just have to use whatever cookie name the server is expecting?

**Comment by NTaylorMullen** [comment]
> Wouldn't the client just have to use whatever cookie name the server is expecting?


Yes, that's the "magic string" part of it. For example see this reconstruction of a request:

```
document.cookie="MagicCookieName=@token.CookieToken";
$.ajax({
    url: "...",
    contentType: "application/json",
    data: JSON.stringify({}),
    type: "POST",
    headers: {
        "@token.HeaderName": @token.RequestToken
    }
});
```

Basically, you configure antiforgery in your startup and then you have no way to retrieve what the `CookieName` was configured to.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2416
