### ISSUE TITLE
.net core :Missing option SuppressIdentityHeuristicChecks / How to generate token without consider user identity

### ISSUE THREAD

**Issue by chintan3100** [aspnet/Antiforgery#157]
I am working with SPA which communicates with .net core web API. UI and API both are on a different domain.
On login API I am generating JWT token + anti-forgery token but this token is not valid due to identity set to "".
There should option like SuppressIdentityHeuristicChecks = false.

Is there any other way?
For temporary soluton.
I created separate API which generates anti-forgery token. So after login UI will call getAntiforgery token API with jwt token. So every time there two web call when user try to login.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2413
