### ISSUE TITLE
SignoutAsync doesn't remove Antiforgery cookie

### ISSUE THREAD

**Issue by jchannon** [aspnet/Antiforgery#167]
Calling `SignOutAsync("MyCookieMW", authProperties);` only removes the authentication cookie in the app not the antiforgery cookie that is created.

**Comment by Eilon** [comment]
@blowdart / @rynowak - this seems reasonable to me in principle, though the two features are not directly related. Thoughts on this?

**Comment by rynowak** [comment]
It seems like an improvement to me. Your cookie won't be valid after your identity changes.

Not sure off the cuff how we'd accomplish this, but it's worth a look.

-------

However, if we do implement something like it doesn't mean that applications/frameworks can rely on it. It's just a nicety

**Comment by jchannon** [comment]
As a side note when you say your forgery cookie won't be valid when the
identity changes does this apply to sliding auth to? From what I've
experienced this isn't the case ie cookie auth cookie regenerates after X
minutes due to sliding auth but I can still post data successfully.

**Comment by rynowak** [comment]
>  ie cookie auth cookie regenerates after X minutes due to sliding auth but I can still post data successfully

Actually I spoke wrongly before. The cookie token is a unique token that acts like a salt. It's the 'request' (usually form-data) token that contains the claim-related data.

**Comment by brockallen** [comment]
Perhaps what should happen is the anti-forgery should check if the current forgery token matches the current authenticated user, and if not ignore the cookie for the incoming request, and remove it on the response.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2411
