### ISSUE TITLE
An exception was thrown while deserializing the token on Ubuntu

### ISSUE THREAD

**Issue by dexterhussain** [aspnet/Antiforgery#173]
We are developing a project using anti-forgery in dotnet core 2.0 . We are making this project on windows machine no redis nothing but as soon as I publish this to ubuntu it gives me these errors,

: Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery[7]
An exception was thrown while deserializing the token.
System.InvalidOperationException: The antiforgery token could not be decrypted. ---> System.Security.Cryptography.CryptographicException: The payload was invalid.

**Comment by dexterhussain** [comment]
Gives no errors on Windows Development Machine

**Comment by mkArtakMSFT** [comment]
@dexterhussain, can you please share a project with a repro?
@blowdart, any thoughts regarding this?

**Comment by blowdart** [comment]
Did you configure data protection yet? On linux there's no safe way for data protection to store keys, unlike on Windows, so you need to make a specific choice on how you want your keys saved.

Start with the file system, then layer an X509 certificate on top if you feel it's needed. https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?tabs=aspnetcore2x

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2409
