### ISSUE TITLE
Determine if the antiforgery cookie is considered essential

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Antiforgery#175]
RE: aspnet/Security#1561

When this new policy is applied all non-essential cookies will be suppressed. We need to determine if anti-forgery is considered essential by default. I expect yes as it's a security feature.

@blowdart

**Comment by rynowak** [comment]
I also expect yes.

**Comment by blowdart** [comment]
Yup, essential

**Comment by mkArtakMSFT** [comment]
Thanks guys. Agree, this should be marked as essential. I'm updating the title and assigning to someone to make the actual change.

**Comment by mkArtakMSFT** [comment]
Hi @kichalla. Can you please mark the antiforgery cookie as "essential"?

**Comment by Tratcher** [comment]
Preview2? @blowdart isn't the rest of this feature going into preview1?

**Comment by blowdart** [comment]
I believe so, but it's a question for @DamianEdwards though

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2408
