### ISSUE TITLE
Setting the Machine Key as usual? ... or any other gotchas for web farm scenarios?

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Antiforgery#19]
We'll be setting the Machine Key as usual for .NET 5 apps using Antiforgery in web farm scenarios, correct?

If so, this might be a feature request: Any interest in providing some control of the Machine Key somewhere in `Startup.cs` (or does that already exist)? Continuing to use `web.config` sucks, and IIS settings are inconvenient.

Besides the Machine Key, are there any other gotchas we should be aware of with Antiforgery in a web farm scenario?

**Comment by GuardRex** [comment]
Related: https://github.com/aspnet/Home/issues/240

@GrabYourPitchforks, was a sample ever produced for setting Machine Key (for Antiforgery for example) using https://github.com/aspnet/dataprotection?

**Comment by danroth27** [comment]
@blowdart

**Comment by blowdart** [comment]
Incorrect.

There's no such thing as Machine Key any more. 

Instead you need to configure [data protection](https://docs.asp.net/en/latest/security/data-protection/index.html) to use a shared key ring. 

How you do this depends on your web farm setup. The simplest example would be an NTFS share, which is a scenario we support out of the box - https://docs.asp.net/en/latest/security/data-protection/configuration/overview.html 

```c#
public void ConfigureServices(IServiceCollection services)
{
    services.AddDataProtection();
    services.ConfigureDataProtection(configure =>
    {
        configure.PersistKeysToFileSystem(new DirectoryInfo(@"\\server\share\directory\"));
    });
}
```

You should be aware that this results in an unprotected key ring - as we can't use DPAPI once the keyring leaves the local machine, nor can we use the ACLed registry. However you can protect the keyring using an X509 certificate;

```c#
public void ConfigureServices(IServiceCollection services)
{
    services.AddDataProtection();
    services.ConfigureDataProtection(configure =>
    {
        configure.PersistKeysToFileSystem(new DirectoryInfo(@"\\server\share\directory\"));
        configure.ProtectKeysWithCertificate("thumbprint");
    });
}
```

Now you need to ensure every machine has the X509 certificate installed on it, and the process IDs you're running your app as have [access to the private key](http://geekswithblogs.net/SoftwareDoneRight/archive/2011/03/15/how-to-set-x509-certificate-private-key-access-rights-for.aspx) and that the key is trusted by the local machines (if it's self signed and not from a CA you already trust). When the certificate expires you'll need to configure the app to look at a new, valid cert (and restart), if you leave the old cert in the cert store it'll still be used to decrypt previously encrypted keys just fine.

If you don't like file shares you can implement your own [IKeyManager](https://docs.asp.net/en/latest/security/data-protection/extensibility/key-management.html) and put them in a database, an HSM, whatever you like

**Comment by DalSoft** [comment]
Sorry to resurrect a closed issue, but this is important and needs to be in the documentation. As it stands Antiforgery won't work easily with Azure Websites as far as I can see https://github.com/aspnet/DataProtection/issues/92

**Comment by blowdart** [comment]
@DalSoft  What do you mean it doesn't work in Azure websites? It works just fine. It doesn't work with slots, but that's Azure's decision not ours, and you can instead use table storage.

**Comment by DalSoft** [comment]
@blowdart sorry I was reading some older information I can now see there are lots of options blob storage, redis and even the machine key if your still targeting net46.

https://www.nuget.org/packages?q=Microsoft.AspNetCore.DataProtection

If I use a multi instance Azure Web App with ARR off, and don't configure shared storage using one of the packages above does Antiforgery work?

**Comment by blowdart** [comment]
Azure web sites will share a keyring automatically, however it is not shared between slots, so if you do AB testing, or do a slot swap to get from pre-production to production then the keys change, and everyone gets logged out. That was there in 1.0

Additionally there is no static, config based key any more (like machine key), it's all keyring based, with rotation and automatically generated keys, hence the need for shared storage.
