### ISSUE TITLE
Add functional test that runs the sample site and verifies it works

### ISSUE THREAD

**Issue by Eilon** [aspnet/Antiforgery#22]

**Comment by ryanbrandenburg** [comment]
@Eilon I started to work on this then realized something similar exists in MVC repo. Do we just want to move that to the Antiforgery repo? If not what are the differences we want to cover?

**Comment by rynowak** [comment]
The purpose of having a test is to make sure the sample works and keeps working.

**Comment by ryanbrandenburg** [comment]
Closed in #33
