### ISSUE TITLE
Improve the performance of Antiforgery

### ISSUE THREAD

**Issue by rynowak** [aspnet/Antiforgery#23]
Right now the cost of using `@Html.Antiforgery` is about 7.5kb / request. In the context of a small MVC form, this is about 15% of the total bytes. We can do much better.

Some places to start looking.

Strings:
![image](https://cloud.githubusercontent.com/assets/1430011/11316049/71f184c6-8fb2-11e5-9ac2-b95493e37d4b.png)

Bytes:
![image](https://cloud.githubusercontent.com/assets/1430011/11316055/84dac3c2-8fb2-11e5-8163-f9ec2c2ad58a.png)

**Comment by dougbu** [comment]
@rynowak this report duplicates existing issues such as #3123 since `new HtmlString()` is used to make things worse in `@Html.Antiforgery()`. I'll ignore anti-forgery over the weekend. But let's discuss possible overlaps on Monday.

**Comment by rynowak** [comment]
Let's talk about avoiding overlap then :+1: I didn't realize part of this was already tracked.

The byte[] stuff AFAIK is hitherto untracked work.

**Comment by Eilon** [comment]
@dougbu please continue to work with @rynowak on how to approach this.

**Comment by dougbu** [comment]
- 492c079
- 0ddfa5f
- At least one more bit coming after extending the `WebEncoders.Base64UrlEncode()` / `WebEncoders.Base64UrlDecode()` API.

**Comment by rynowak** [comment]
We should also verify that we're not paying the cost of re-serializing the cookie token when a request provides one. Here's the scenario:

**Request 1** GET /Products/Edit/5
Client: no tokens provided
Server: sets cookie token and renders request token in the form

**Request 2** POST /Products/Edit/5
Client: provides cookie token and request token
Server: 
    - deserializes the cookie and request token for validation
    - server does not need to set the cookie as it's already set
    - server does a redirect to /Products

Our memory profiling doesn't capture this scenario because we're not using cookies.

**Comment by dougbu** [comment]
FYI @rynowak I'm doing the check you suggest. Suspect all is well because `tokenSet.IsNewCookieToken` handling at least appears correct.

**Comment by dougbu** [comment]
In @rynowak's scenario, Antiforgery avoids the (significant) overhead of adding the cookie token to the response headers. But MVC uses `IAntiforgery.GetHtml()` and that invokes `IAntiforgery.GetAndStoreTokens()` which is `public` and unconditionally returns the full token set. This means the cookie token is re-serialized even when unchanged. The caller doesn't even examine the token set.

Quick fix for this particular useless work coming soon...

**Comment by rynowak** [comment]
Let's catch up to chat about your changes real quick, this is related to something I was working on.

**Comment by dougbu** [comment]
Part 3 for @rynowak [scenario](https://github.com/aspnet/Antiforgery/issues/23#issuecomment-179313157): 73695fc

**Comment by rynowak** [comment]
@dougbu - what's the status of this now that 3 parts of work have been done? Is there anything left to do? What do the numbers look like?

**Comment by dougbu** [comment]
That wasn't the part 3 that I [originally planned](https://github.com/aspnet/Antiforgery/issues/23#issuecomment-178929139). Numbers are now as shown in the #51 After pic. Working on the web encoding (last) bit now.

**Comment by dougbu** [comment]
Part 4: 478edc1 and aspnet/HttpAbstractions@8c120a0
