### ISSUE TITLE
DefaultAntiforgery.SaveCookieTokenAndHeader should not override stricter X-Frame-Options headers

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Antiforgery#60]
Currently, `SaveCookieTokenAndHeader` always replaces the `X-Frame-Options` header with its own value, even if a stricter header has already been added to the response headers by another middleware (e.g NWebsec).

Of course, `SuppressXFrameOptionsHeader` could be used to prevent `SaveCookieTokenAndHeader` from updating the `X-Frame-Options` header but I believe it would be better to add a check to avoid overriding it in this case, specially if the existing header is stricter (i.e uses DENY).

/cc @blowdart

**Comment by blowdart** [comment]
Not sure we want to evaluate "Stricter". This probably indicates nwebsec should be further down the pipeline though.

**Comment by PinpointTownes** [comment]
> This probably indicates nwebsec should be further down the pipeline though.

I don't think it would work. At least, not with MVC, as it's terminating when it handles a request.

Another option for NWebsec would be to apply the security headers after invoking `await next()`. Sadly, this has serious implications and would likely require buffering (or it wouldn't be able to replace the response headers).

**Comment by rynowak** [comment]
> Not sure we want to evaluate "Stricter". This probably indicates nwebsec should be further down the pipeline though.

I'd suggest we change this feature to set the value of the header only if unset. If you set this header already then you did it on purpose.

**Comment by Eilon** [comment]
@rynowak yeah that would seem to follow a common pattern we have elsewhere.
