### ISSUE TITLE
`Microsoft.AspNet.Antiforgery.DefaultAntiforgery.ValidateRequestAsync` always fails

### ISSUE THREAD

**Issue by IEvangelist** [aspnet/Antiforgery#61]
I have attempted to follow the sample source provided [here](https://github.com/aspnet/Antiforgery/tree/1.0.0-rc1/samples/AntiforgerySample). I'm currently using `"Microsoft.AspNet.Antiforgery": "1.0.0-rc1-final"`. The sample source code seems to work "ok" but I really want something more like the current version [here](https://github.com/aspnet/Antiforgery/tree/dev/samples/AntiforgerySample).

I need the ability to use the Cookie approach for my **Angular2** application. How can I achieve? Here is the middleware that I'm attempting to use:

```csharp
    public class AntiforgeryMiddleware
    {
        private readonly IAntiforgery _antiforgery;
        private readonly AntiforgeryOptions _options;
        private readonly RequestDelegate _next;

        public AntiforgeryMiddleware(RequestDelegate next,
                                     IAntiforgery antiforgery,
                                     IOptions<AntiforgeryOptions> options)
        {
            _next = next;
            _antiforgery = antiforgery;
            _options = options.Value;
        }

        public async Task Invoke(HttpContext context)
        {
            if (string.Equals("GET", context.Request.Method, StringComparison.OrdinalIgnoreCase))
            {
                var tokenSet = _antiforgery.GetAndStoreTokens(context);
                if (tokenSet.CookieToken != null)
                {
                    context.Response.Cookies.Append(_options.CookieName, tokenSet.CookieToken, new CookieOptions {HttpOnly = false});
                }
            }
            else if (string.Equals("POST", context.Request.Method, StringComparison.OrdinalIgnoreCase))
            {
                // At this point the context.Request.Headers has my cookie token
                // But if I were to invoke _antiforgery.GetTokens(context), it wouldn't have a cookie token!
                await _antiforgery.ValidateRequestAsync(context);
            }

            await _next(context);
        }
    }
```

The odd thing is that in the `context.Request.Headers` I have the cookie token that I'm expecting, however; the current `Microsoft.AspNet.Antiforgery.DefaultAntiforgery.ValidateRequestAsync` function seems to expect both a cookie and a form token -- which I believe is incorrect. Please help...

**Comment by rynowak** [comment]
Our antiforgery system uses two tokens.

The "cookie" token is set in a cookie and will be sent back by the browser automatically with every request.

The "request" token should be rendered as part of a page [see here](https://github.com/aspnet/Antiforgery/blob/1.0.0-rc1/samples/AntiforgerySample/FormPostSampleMiddleware.cs#L36). The client needs to send it back to the server in a form post (rc1-rc2), or header (rc2).

The form approach is 'automatic' for traditional browser based apps. The header approach is supported by most client-side frameworks, but unfortunately the server side code for it was added in RC2.

The reason why something other than a cookie is required is that **cookies are the CSRF vulnerability**. If the system worked on cookies alone it wouldn't protect anything.

-------------

Here's what's missing from your code and how you might made it work.

```
var tokenSet = _antiforgery.GetAndStoreTokens(context);
if (tokenSet.RequestToken != null)
{
    context.Response.Cookies.Append("XSRF_TOKEN", tokenSet.RequestToken, new CookieOptions {HttpOnly = false});
}
```

This code will put the "request" token in the `XSRF-TOKEN` cookie. This is where angular will look by default https://docs.angularjs.org/api/ng/service/$http - unless it's changed in angular 2.

When angular sees this cookie, it will send the value back in the `X-XSRF-TOKEN` header.

Your comment:
```
// At this point the context.Request.Headers has my cookie token
// But if I were to invoke _antiforgery.GetTokens(context), it wouldn't have a cookie token!
```

Doesn't seem quite right. `context.Request.Headers["X-XSRF-TOKEN"]` has the request token, but the RC1 version of antiforgery doesn't look there.

Try adding the following before your call to `ValidateRequestAsync`. 
```
// This won't be required in RC2
var dictionary = new Dictionary<string, StringValues>();
dictionary.Add(_options.FormFieldName, context.Request.Headers["X-XSRF-TOKEN"]);
context.Request.Form = new FormCollection(dictionary);
await _antiforgery.ValidateRequestAsync(context);
```

If you have other form data, you'll need to copy it as well.

**Comment by IEvangelist** [comment]
I'm not doing a form's post, I'm doing _Web API_ calls. I certainly should have prefaced this with that initially. I started down the route of using the `ValidateAntiForgeryTokenAttribute` with corresponding `@Html.AntiForgeryToken()` but realized that wouldn't work for my _Web API_ calls as I'm not posting the "__RequestVerificationToken" generated as a hidden input. I then stumbled upon the `Antiforgery` library here which seemed to be exactly what I was looking for. From the sounds of it, **RC2** is the golden ticket that I have been waiting for. I have found that there are actually many, many things that I have been looking forward to from **RC2**.

I guess we can simply close this issue and revisit it once if need be once **RC2** is made available.

Thank you,

**Comment by rynowak** [comment]
Ok, thanks - the workaround for copying the header value into form-values should work on RC1 if you need this sooner.

**Comment by IEvangelist** [comment]
It threw an exception claiming that the form and cookie tokens were swapped.

**Comment by rynowak** [comment]
Can you paste in your code? (or just ignore if you'd rather not mess with this until RC2 is available)

**Comment by IEvangelist** [comment]
I don't have it with me right now, away from my PC. But I'm confused how you think this will work, there is no form being posted - how does that work when it's just an API HTTP POST? The `content-type` is `application/json` not any of the valid form types?

**Comment by rynowak** [comment]
The code that I shared manually copies the request token into the form. It's a workaround, but I believe the RC1 code will still look at the form data if you're using `ValidateRequestAsync` regardless of content type.

**Comment by IEvangelist** [comment]
RC1 only has a CookieToken and FormToken, I do not see a RequestToken. At this point, I'll just wait for RC1 -- I hope it comes soon.  :)

Thanks for your help!
