### ISSUE TITLE
AntiforgeryOptions.RequireSsl enhancement

### ISSUE THREAD

**Issue by AerisG222** [aspnet/Antiforgery#7]
The current implementation enforces that if this option is enabled that the incoming request must occur over SSL.  This causes an issue when you have SSL terminated on a frontend server, such as hosting a site on nginx.

The authentication system allows for the secure flag to be set regardless of the SSL state of the request.  See: https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication.Cookies/CookieAuthenticationOptions.cs  and https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication.Cookies/CookieSecureOption.cs.  With that, using the setting of 'Always' allows the cookie to be marked secure even with SSL termination in front of aspnet.

Please consider updating the implementation to be more consistent with the authentication system, which will also support more hosting scenarios.

Thanks!

**Comment by danroth27** [comment]
We should remove the RequireSsl option and adopt the same options as the cookie middleware for configuring the cookie security.

**Comment by Tratcher** [comment]
@AerisG222 for reverse proxy scenarios it's recommended that the scheme be forwarded from the proxy and applied to the request. Without this you'll have trouble generating correct links, etc..

/cc: @blowdart

**Comment by AerisG222** [comment]
@Tratcher what is the scenario you are thinking where the links (etc) would not be properly generated?  In my scenario, I am forcing SSL throughout the entire site, so do not have scenarios of flipping schemes, and links within the application work as expected because they do not specify scheme or host for that matter.

Additionally, I believe it is somewhat common for sites to perform SSL offloading which is another variation of this scenario.

I realize there is benefit with end to end encryption, but wonder if it needs to be required on both the front and back (i.e. kestrel).  If that is required,  SSL must be configured in 2 places rather just on the front end webserver.  If the final approach is to require SSL on both ends, guidance/documentation would be appreciated, in particular regarding the configuration of kestrel.

**Comment by Tratcher** [comment]
I didn't say you needed to use HTTPS between your front-end and your back-end, I said your front-end needs to tell the back-end that HTTPS was used on the public connection. A common way of doing this is for the front-end to set the x-forwarded-proto header, and for the back-end to update the Request.Scheme field accordingly. The OverrideHeaderMiddleware (https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNet.HttpOverrides/OverrideHeaderMiddleware.cs#L73) and IISPlatformHandlerMiddleware (https://github.com/aspnet/IISIntegration/blob/dev/src/Microsoft.AspNet.IISPlatformHandler/IISPlatformHandlerMiddleware.cs#L69) do this.  If your site only accepts offloaded HTTPS connections then you can do something even simpler:
```
app.Use((context, next) =>
{
  context.Request.Scheme = "https";
  return next();
});
```

Components like the Authentication middleware need to generate absolute URIs for redirects as they interact with 3rd party sites. https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication/AuthenticationHandler.cs#L114 Behind an ssl terminating proxy these would generate incorrect http redirects unless the request scheme was updated accordingly.

**Comment by AerisG222** [comment]
@Tratcher  thanks for the explanation, this is very helpful.  I was not aware of the middleware you referenced, thank you for pointing that out.

I don't appreciate all the details, but this still feels a bit inconsistent.  Per the above comment, I believe the system will provide a means to support this scenario as is.

@kichalla if there is no additional work for this, please feel free to close.  Otherwise, I'll leave this open for you to continue to track this effort.

Thanks

**Comment by kichalla** [comment]
Thanks @AerisG222 ...I will close this for now.
