### ISSUE TITLE
Should AntiForgery use ITlsTokenBindingFeature for DataProtection?

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Antiforgery#76]
See https://github.com/aspnet/Security/issues/773
https://github.com/aspnet/Antiforgery/blob/0c81df859145801d2846ccbdc9af5830fa791f63/src/Microsoft.AspNetCore.Antiforgery/Internal/DefaultAntiforgeryTokenSerializer.cs#L55

Only apply it if AntiforgeryOptions.RequreSsl is true.

**Comment by Eilon** [comment]
@Tratcher @blowdart - I believe this still isn't doable in 2.0.0, is that correct?

**Comment by Tratcher** [comment]
Correct, still backlogged.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2420
