### ISSUE TITLE
How do I use app.Map and ValidateRequestAsync with app.UseMvc?

### ISSUE THREAD

**Issue by rbjarnason** [aspnet/Antiforgery#82]
I've been trying to get this to work for a while and find few examples. Actually this quite elegant method of antiforgery prompted me to upgrade from RC1 to RC2, which was a bit painful but everything is working now, except this.

Here is my code that is based on your angular.js example, I only have problem with the last part app.Map() that is causing the request to stop even if its a "GET" request - an empty response comes back.  Any ideas?

```c#
app.Use(next => context =>
{
    if (
        string.Equals(context.Request.Path.Value, "/", StringComparison.OrdinalIgnoreCase) ||
        string.Equals(context.Request.Path.Value, "/index.html", StringComparison.OrdinalIgnoreCase))
    {
        // We can send the request token as a JavaScript-readable cookie, and Angular will use it by default.
        var tokens = antiforgery.GetAndStoreTokens(context);
        context.Response.Cookies.Append("XSRF-TOKEN", tokens.RequestToken, new CookieOptions() { HttpOnly = false });
    }

    return next(context);
});

// Configure the HTTP request pipeline.
app.UseDefaultFiles();
app.UseStaticFiles();

app.UseSession();

// Add MVC to the request pipeline.

app.Map("/api", a => a.Run(async context =>
{
    if (string.Equals("POST", context.Request.Method, StringComparison.OrdinalIgnoreCase))
    {
        // This will throw if the token is invalid.
        await antiforgery.ValidateRequestAsync(context);  
    }
}));

app.UseMvc();
```

**Comment by brockallen** [comment]
I can't tell if you know this already or not, but a Map forks the pipeline -- IOW, your "/api" path doesn't automatically then join back up with middleware outside of the "Map". In short, MVC won't run if the request starts with "/api" due to the fork.

**Comment by rbjarnason** [comment]
Thanks @brockallen for the info.  I've tried different combinations of this, trying to use app.Use and app.Run directly.  I don't need it to branch so I should probably not be using app.Map but this is the only example I could find for ValidateRequestAsync.

**Comment by Eilon** [comment]
@rbjarnason what if you change the call to `app.Map()` to instead be `app.Use()` and then call `next(context)` at the end? That's basically what your first `app.Use` is doing, but then also doing it for anti-forgery.

**Comment by rbjarnason** [comment]
Thanks @Eilon its working now like this :)

```c#
app.Use(next => async context =>
{
    if (string.Equals("POST", context.Request.Method, StringComparison.OrdinalIgnoreCase))
    {
        // This will throw if the token is invalid.
        await antiforgery.ValidateRequestAsync(context);  
    }
    await next(context);
});

app.UseMvc();
```

**Comment by Eilon** [comment]
@rbjarnason great!
