### ISSUE TITLE
Rename ServiceCollectionExtensions to AntiforgeryServiceCollectionExtensions

### ISSUE THREAD

**Issue by Eilon** [aspnet/Antiforgery#84]
Rename `ServiceCollectionExtensions` to `AntiforgeryServiceCollectionExtensions` so that the type name is not ambiguous across other assemblies.

**Comment by Eilon** [comment]
@danroth27 FYI

**Comment by NTaylorMullen** [comment]
54d9860eeae05baf39006b499c9c7af3f1350814
