### ISSUE TITLE
Discussion: Antiforgery service collection extension class has been renamed to avoid ambiguity

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Antiforgery#86]
`Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions` => `Microsoft.Extensions.DependencyInjection.AntiforgeryServiceCollectionExtensions`

Associated announcement: https://github.com/aspnet/Announcements/issues/187

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
