### ISSUE TITLE
How do I retrieve the antiforgery token in RC2 ?

### ISSUE THREAD

**Issue by pingcrosby** [aspnet/Antiforgery#90]
Hi
With .NET Core RC1 the following code to validate an antiforgery token worked.  I can see that the api has changed in RC2 

RC1 Working code
```
using Microsoft.AspNet.Antiforgery;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Filters;
using Microsoft.Extensions.OptionsModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FortMembership.Filters
{

    public class ValidateAntiForgeryHeaderToken : TypeFilterAttribute
    {
        public ValidateAntiForgeryHeaderToken() : base(typeof(ValidateAntiForgeryHeaderTokenImpl))
        {
        }
        
        // see https://docs.asp.net/en/latest/mvc/controllers/filters.html
        //
        // If you have a simple filter that doesn’t require any arguments, but which has constructor dependencies that need to be filled by DI, 
        // you can inherit from TypeFilterAttribute, allowing you to use your own named attribute on classes and methods (instead of [TypeFilter(typeof(FilterType))]). 
        //

        private class ValidateAntiForgeryHeaderTokenImpl : IAsyncAuthorizationFilter
        {
            private readonly IAntiforgery _antiforgery; 

            public readonly string verificationToken = "X-VerificationToken";
            public readonly string antiforgeryCookieName;

            public ValidateAntiForgeryHeaderTokenImpl(IAntiforgery antiforgery, IOptions<AntiforgeryOptions> antiforgeryOptions)
            {
                _antiforgery = antiforgery;
                antiforgeryCookieName = antiforgeryOptions.Value.CookieName; // if not specified this is autogenerated by mvc
            }

            public Task OnAuthorizationAsync(AuthorizationContext context)
            {
                string headerToken = context.HttpContext.Request.Headers[verificationToken];
                if (headerToken != null)
                {                     
                    string antiForgeryCookieValue = context.HttpContext.Request.Cookies[antiforgeryCookieName];
                    _antiforgery.ValidateTokens(context.HttpContext, new AntiforgeryTokenSet(headerToken, antiForgeryCookieValue)); // throws on invalid 
                    return Task.FromResult<object>(null);
                }
                return _antiforgery.ValidateRequestAsync(context.HttpContext);               
            }
        }
    }
}
```
Can you point me in the right direction with RC2 , I cannot see the API calls necessary to create a new tokenset and validate 

` return await _antiforgery.ValidateRequestAsync(context.HttpContext, /* new AntiforgeryTokenSet(headerToken, antiForgeryCookieValue */));`

Thanks

**Comment by dougbu** [comment]
The `IAntiforgery` interface includes `SetCookieTokenAndHeader(HttpContext)`. But while a few methods return an `AntiforgeryTokenSet`, none have parameters of that type.

Could changing `AntiforgeryOptions` in your `Startup` avoid the need for `ValidateAntiForgeryHeaderToken ` entirely?

**Comment by rynowak** [comment]
@pingcrosby - we added support for headers to antiforgery as a feature in RC2. Is that what you're trying to do? https://github.com/aspnet/Antiforgery/blob/dev/samples/AntiforgerySample/Startup.cs#L21

If you're using MVC all your have to do is configure this setting to the desired header name and all of the built in validation will use it.

**Comment by pingcrosby** [comment]
That exactly what i wanted.
Nice and simple - as an aside is it possible to add multiple headers to check against eg
A quick question :-
    Is it possible to add multiple headers to check against ? eg
` services.AddAntiforgery(options => options.HeaderName = "X-XSRF-TOKEN_TYPE1");
 services.AddAntiforgery(options => options.HeaderName = "X-XSRF-TOKEN_TYPE2");`

When i add `options.HeaderName = "X-XSRF-TOKEN` does this mean `@Html.AntiForgeryToken()` generates a Hidden field named X-XSRF-TOKEN or are they independent on one another?

I ask this because i have some legacy code to port and it mixes `@Html.AntiForgeryToken()` and some Ajax code that places the token in the header but uses a different name that generated by AntiForgeryToken.

**Comment by rynowak** [comment]
> Is it possible to add multiple headers to check against ? eg

We don't have any built-in support for this


> When i add options.HeaderName = "X-XSRF-TOKEN does this mean @Html.AntiForgeryToken() generates a Hidden field named X-XSRF-TOKEN or are they independent on one another?

Yes, `@Html.AntiForgeryToken()` will still generate the hidden field. We've also updated `@Html.BeginForm` and the form TagHelper to include an antiforgery token by default, so most calls of `@Html.AntiForgery()` in legacy code are redundant.

**Comment by pingcrosby** [comment]
Thanks for clarifying this issue 

Appreciated
