### ISSUE TITLE
Antiforgery Token used by AngularJS

### ISSUE THREAD

**Issue by anil2** [aspnet/Antiforgery#94]
I was trying to follow the sample code provided for AntiForgery 
There anti-forgery token is written to a cookie where AngularJS (Javascript) can read it and use it on every  subsequent XHR requests.

I see that even when the same token is used more than once, It is considered to be a valid token and everything is just normal. When and how an issued token gets invalid? 

If the token can be used more than once, how is it secure to use it with AngularJS (Javascript)? 
What happens if malicious code get access to this token?

**Comment by ShadowDancer** [comment]
This token does not defend against malicious code. Check this: https://en.wikipedia.org/wiki/Cross-site_request_forgery

**Comment by rynowak** [comment]
@ShadowDancer is correct - CSRF can protect you from another website making malicious requests to yours, but it cannot protect you from XSS.

/cc @blowdart

**Comment by blowdart** [comment]
Tokens get issued when you first come to a form that has a token embedded in in. A corresponding cookie is dropped, and it lasts for the browser session.

**Comment by anil2** [comment]
thank you so much for the information, it really helps @ShadowDancer @rynowak @blowdart
