### ISSUE TITLE
How to set the cookie name?

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Antiforgery#97]
I've tried with both ...
```c#
services.AddAntiforgery(options => 
{
    options.CookieName = "MY_X-XSRF-COOKIE";
    options.HeaderName = "MY_X-XSRF-TOKEN";
});
```
... and ...
```c#
services.Configure<AntiforgeryOptions>(options =>
{
    options.CookieName = "MY_X-XSRF-COOKIE";
    options.HeaderName = "MY_X-XSRF-TOKEN";
});
```
... but I'm only getting ...
```
.AspNetCore.Antiforgery.uZGDUqdnfBA=...................................; 
```
[EDIT] I looked at the repo tests, and this looks correct. I feel that I'm missing something simple here.

**Comment by rynowak** [comment]
Can you include all of your `ConfigureServices` method? Something's fishy here.

**Comment by GuardRex** [comment]
oooo! I just discovered that I added the service twice by accident. Let me remove that first one and see what happens. brb

**Comment by GuardRex** [comment]
I'm not sure if I was looking in the right place (i.e., a page that didn't have a `<form>` or if it was just that I had two calls to setup the service. Whatever I did wrong, this works ... I see it now.

Sorry for the bother ... I do have a **real** question coming up on an existing issue wrt token expiry.

**Comment by rynowak** [comment]
ok :+1: glad it's sorted out
