### ISSUE TITLE
TryValidateTokenSet null tokens don't flow well for custom use of this method

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Antiforgery#99]
When attempting to manually generate and consume time-limited tokens (https://github.com/aspnet/Antiforgery/issues/36#issuecomment-237604605), I'm using `TryValidateTokenSet` directly, but when either of the tokens are set to `null` (as I have setup in my own `Deserialize` method when DP says that the token is expired ... I just return `null` for the token), the `TryValidateTokenSet` method doesn't flow the result and message well for me at https://github.com/aspnet/Antiforgery/blob/37c8f5de70c0e446a1842064d70b2094c039ad4a/src/Microsoft.AspNetCore.Antiforgery/Internal/DefaultAntiforgeryTokenGenerator.cs#L121

Here's how null tokens are handled now. They throw ...

``` c#
if (cookieToken == null)
{
    throw new ArgumentNullException(
        nameof(cookieToken),
        Resources.Antiforgery_CookieToken_MustBeProvided_Generic);
}
if (requestToken == null)
{
    throw new ArgumentNullException(
        nameof(requestToken),
        Resources.Antiforgery_RequestToken_MustBeProvided_Generic);
}
```

It looks like it wasn't a prob for the original specification for antiforgery, because the only null tokens are those that aren't part of the request in the first place. I see the tests very early on for the cookie and either header or body request token being `null` (missing from the request). If missing, I see they get handled prior to the validation attempt. I guess the original thinking was that in `TryValidateTokenSet` `null` would never be a "good" value to get back out of deserialization. However, that's exactly the case here.

It's better for me to return a null token from deserialization when the DP throws claiming that the token is expired. I can't very well return an actual token. :smile: Since for me, a null token is fine out of deserialization, I'd like to just have `TryValidateTokenSet` flow it back to the caller cleanly just like the rest of the validation failures there ...

``` c#
if (cookieToken == null)
{
    message = Resources.Antiforgery_CookieToken_MustBeProvided_Generic;
    return false;
}
if (requestToken == null)
{
    message = Resources.Antiforgery_RequestToken_MustBeProvided_Generic;
    return false;
}
```

I realize I can replace the method, but it would make it easier to consume the result of this OOB method if it were built-in. I would like to just do this ...

``` c#
if (!tokenGenerator.TryValidateTokenSet(
    HttpContext,
    deserializedCookieToken,
    deserializedRequestToken,
    out message))
{
    // Log message here
    return HttpStatusCode.BadRequest;
}
return HttpStatusCode.OK;
```

but if I don't replace this method, then I'm stuck having to do this ...

``` c#
try
{
    if (!tokenGenerator.TryValidateTokenSet(
        HttpContext,
        deserializedCookieToken,
        deserializedRequestToken,
        out message))
    {
        // Log message here
        return HttpStatusCode.BadRequest;
    }
}
catch (System.Exception ex)
{
    // Log exception here (for me, this will prob be an expired token out of DP)
    return HttpStatusCode.BadRequest;
}
return HttpStatusCode.OK;
```

**Comment by Eilon** [comment]
Would it be easiest if we just added built-in support for time-limited tokens? It's not clear to us exactly what's going on in the code shown above, but we could certainly look at just building the feature.

**Comment by GuardRex** [comment]
@Eilon wow ... I forgot about this one. I'm not even working with this any longer. No one else is asking for this, so it seems like this one should be closed.

> not clear to us exactly what's going on in the code shown above

I was just suggesting that instead of ...
```c#
if (cookieToken == null)
{
    throw new ArgumentNullException(
        nameof(cookieToken),
        Resources.Antiforgery_CookieToken_MustBeProvided_Generic);
}
```
that method did this ...
```c#
if (cookieToken == null)
{
    message = Resources.Antiforgery_CookieToken_MustBeProvided_Generic;
    return false;
}
```
... similar to the way other tests in the method are handled.

... instead of throwing an exception, I was just hoping `tokenGenerator.TryValidateTokenSet()` would come back `false`.

Still tho ..... I'm not using this any longer ... no one else is asking for this ... you can close this.

**Comment by Eilon** [comment]
Ah, ok, no worries! Sorry for taking so long to get back to you on this.
